### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_3rdparty#107]
Now it will be time to release a new version:

- Upgrade julius to v4.4.2
- Add ROS Interface for julius both isolated word mode / grammar mode
- Refactor `voice_text` to use service and support machine tag on remote api call
- Bugfix: libsiftfast
- Bugfix: collada_urdf_jsk_patch

CC: Athome members

**Comment by k-okada** [comment]
ok, done https://github.com/ros/rosdistro/pull/15422

**Comment by furushchev** [comment]
@k-okada Thank you very much!!

**Comment by furushchev** [comment]
@k-okada Please also release `voice_text`. it blocks https://github.com/jsk-ros-pkg/jsk_robot/pull/846
