### ISSUE TITLE
fails tweeting with image on PR2

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_3rdparty#14]
pr2 often fails to tweet with image:
https://twitter.com/pr2jsk/status/634221745029820416

```
Amazing! Furushchev has used PR2 for 55 minutes, I'm not tired!
(image not published)
```

`rostwitter` uses `/tmp` to store image published, but PR2 does not share `/tmp` on 2 PCs (c1 and c2), because `rostwitter` could not find image tweeted on another pc.

may be good to store image on `$HOME/.rostwitter`?

**Comment by garaemon** [comment]
Who does save the image?

2015年8月20日木曜日、Furushchev<notifications@github.com>さんは書きました:

> pr2 often fails to tweet with image:
> https://twitter.com/pr2jsk/status/634221745029820416
>
> Amazing! Furushchev has used PR2 for 55 minutes, I'm not tired!
> (image not published)
>
> rostwitter uses /tmp to store image published, but PR2 does not share /tmp
> on 2 PCs (c1 and c2), because rostwitter could not find image tweeted on
> another pc.
>
> may be good to store image on $HOME/.rostwitter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/14>.
>


-- 
✉︎ from iPhone

**Comment by furushchev** [comment]
Or scp image to host which executes tweet.py when needs?
(maybe need to change `jsk_robot_start/lifelog/tweet_client.l`)

**Comment by k-okada** [comment]
so you need to run iamge_saver at the machine runnning rostwitter

**Comment by furushchev** [comment]
@garaemon every nodes which publishes `/tweet` topic.

**Comment by furushchev** [comment]
@k-okada ok. I'll create PR.

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pepper_robot/jsk_pepper_startup/launch/jsk_pepper_startup.launch#L34

**Comment by k-okada** [comment]
I don think this is rostwitter problem, but pr2 launch file is not correct. see papper case, running rostwitter and image_save at same machine and https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pepper_robot/jsk_pepper_startup/nodes/tweet.l just calls to save images 

(the papper code is same as https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/lifelog/tweet.l#L18, so we need to merge them)

**Comment by garaemon** [comment]
How about saving image inside of rostwitter instead of using image_saver?

**Comment by furushchev** [comment]
is there no problem if we remove the feature to read image topic from parameter `/active_user/image_topic`?

**Comment by k-okada** [comment]
On Thu, Aug 20, 2015 at 4:20 PM, Furushchev <notifications@github.com> 
wrote:

> the feature to read image topic from parameter /active_user/image_topic?
>

what it this? who is reading this topic?

--
◉ Kei Okada

**Comment by furushchev** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/lifelog/tweet_client.l#L5-L8

**Comment by k-okada** [comment]
oh, you can change tweet_client.l to use image_saver, not extract_images

--
◉ Kei Okada
