### ISSUE TITLE
How to use audio raw data?

### ISSUE THREAD

**Issue by Kijung-Kim** [jsk-ros-pkg/jsk_3rdparty#187]
Hi, I am trying to get voice pitch. or some special features.

1. What is the audio raw data (I already search google...google say...not include header data..)

2. How to use audio raw data?

I am waiting for any advice.

thanks for reading.

**Comment by knorth55** [comment]
which package are you talking about?
respeaker_ros? ros_speech_recognition?
if you can paste your code, it would be helpful for us to make good advice.

**Comment by Kijung-Kim** [comment]
"respeaker_ros" is publish 
topic name is "audio" and "speech_audio"

thanks for  reply

**Comment by Kijung-Kim** [comment]
> which package are you talking about?
> respeaker_ros? ros_speech_recognition?
> if you can paste your code, it would be helpful for us to make good advice.

"respeaker_ros"
topic name is "audio" and "speech_audio"

thanks for reply

**Comment by 708yamaguchi** [comment]
`respeaker_node` uses 16 bit audio data, but `/audio and /speech_audio (audio_common_msgs/AudioData)` uses uint8 audio data.
Therefore, you need to convert the data type uint8 <-> 16 bit.
respeaker_node:
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/respeaker_node.py#L226
audio_common_msgs/AudioData:
http://docs.ros.org/jade/api/audio_common_msgs/html/msg/AudioData.html

For the convert, you can refer to these functions:
16 bit -> uint8 (string):
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/respeaker_node.py#L282
uint8 -> 16 bit:
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2478/files#diff-050e42c1f34e0ebf9955769ce6cc4245R65-R66

**Comment by Kijung-Kim** [comment]
> `respeaker_node` uses int16 audio data, but `/audio` and `/speech_audio (audio_common_msgs/AudioData)` uses uint8 audio data.
> Therefore, you need to convert the data type (uint8 <-> int16).
> int16, respeaker_node:
> https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/respeaker_node.py#L254
> uint8, audio_common_msgs/AudioData:
> http://docs.ros.org/jade/api/audio_common_msgs/html/msg/AudioData.html
> 
> For the convert, you can refer to these functions:
> int16 -> uint8 (string):
> https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/respeaker_ros/scripts/respeaker_node.py#L282
> uint8 -> int16:
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/2478/files#diff-050e42c1f34e0ebf9955769ce6cc4245R65-R66

Thank you for your kind answer.

**Comment by knorth55** [comment]
@Kijung-Kim did you solve your problem? if so, please close this issue.
If you have another problem, feel free to open another one.
