### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by brean** [jsk-ros-pkg/jsk_3rdparty#210]
Please add a LICENSE file describing the license for this software.

**Comment by k-okada** [comment]
license is described in package.xml of each package, for example
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/ddcf49704433536449c0d747b8e49f313cbf982a/bayesian_belief_networks/package.xml#L10
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/ddcf49704433536449c0d747b8e49f313cbf982a/dialogflow_task_executive/package.xml#L9
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/ddcf49704433536449c0d747b8e49f313cbf982a/gdrive_ros/package.xml#L10
...

if you find missing / wrong license, let me know.

**Comment by brean** [comment]
Thanks
