### ISSUE TITLE
aques_talk cannot speak numbers and alphabets

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_3rdparty#228]
aques_talk cannot speak numbers now.
we can use tag value for numbers and alphabets.
we need to replace them in `text2wave`.

```bash
<NUM VAL=100> # いち/ぜろ/ぜろ
<NUMK VAL=100> # ひゃく
<NUMK VAL=10 COUNTER=ふん> # じゅっぷん
<ALPHA VAL=fetch> # えふ/いー/てぃー/しー/えいち
```

cc. @mqcmd196 @708yamaguchi 
https://www.a-quest.com/archive/manual/siyo_onseikigou.pdf

**Comment by 708yamaguchi** [comment]
I'm sorry, but I can't open the PDF.
Chrome is saying "Error Failed to load PDF document".
I'll try again after some time.

**Comment by 708yamaguchi** [comment]
I can open the PDF now.
I place the file at Manuals -> JSK robot system in our Google Drive.

**Comment by 708yamaguchi** [comment]
I created PR https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/229

**Comment by 708yamaguchi** [comment]
I checked that fetch1075 can speak number by
```bash
$ rosrun jsk_fetch_startup time_signal.py
```

However, fetch1075 speaks "20ときです"　while the input is "20時です"
This is because I do not consider 助数詞.
I will try to solve this problem.
