### ISSUE TITLE
Do not use sourceforce to install julius

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_3rdparty#29]
sourceforce is unstable, I see connection lost a lot of times.

julius license allows us to redistribute codes.
https://osdn.jp/cvs/view/julius/julius/LICENSE.txt?view=markup

We can move julius codes to github archives.

**Comment by wkentaro** [comment]
libsiftfast is same?
I could find a repo in GitHub forked from sourceforge.

**Comment by garaemon** [comment]
libsiftfast uses svn of sourceforge.
I think large file hosting on sourceforge is more unstable than svn sourceforge

**Comment by garaemon** [comment]
julius has moved to github
https://github.com/julius-speech/julius

**Comment by furushchev** [comment]
This issue is solved by https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/99

**Comment by furushchev** [comment]
@k-okada We can close this now! :+1:
