### ISSUE TITLE
Cannot release jsk_3rdparty because of opencv2

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_3rdparty#34]
on hydro, opencv is provides as opencv2 but on indigo it is provided as libopencv-dev.

bloom failed to resolve package dependency.

**Comment by k-okada** [comment]
ok, fixed in
https://github.com/tork-a/jsk_3rdparty-release/commit/91cf883c226354f4da85634fc10226ac31a3f6de

--
◉ Kei Okada

**Comment by garaemon** [comment]
thank you
