### ISSUE TITLE
[google_chat_ros] Where do you upload your image?

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_3rdparty#400]
@mqcmd196 

in `google_chat_ros`, you use `gdrive_ros` to upload local image and use the URL for chat notification.
My question is where do you usually put your image?
You use your own google drive directory?

cc. @a-ichikura

**Comment by mqcmd196** [comment]
I use Fetch's one, launching `gdrive_ros` with Fetch's credential.

**Comment by mqcmd196** [comment]
When sending image with google chat, permanent link is required for viewing image. So `google_chat_ros` uploads image with gdrive, and gets its link

**Comment by knorth55** [comment]
I made a PR for this issue.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/403
