### ISSUE TITLE
pgm_learner failed to build on jade buildfarm

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_3rdparty#46]
@furushchev 
Fix it

http://www.ros.org/debbuild/jade.html?q=pgm_learner

**Comment by furushchev** [comment]
Sure. what is the error? I could not check on this page.

**Comment by garaemon** [comment]
http://jenkins.ros.org/view/JbinU32/job/ros-jade-pgm-learner_binarydeb_utopic_i386/
missing rostest


alwasy fixed in https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/48

**Comment by furushchev** [comment]
OK. Thank you very much.

**Comment by garaemon** [comment]
I hope maintainer to watch status of ros buildfarm.
