### ISSUE TITLE
sklearn is not released on jade

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_3rdparty#51]
@aginika 

It block jade release of jsk_recognition.

**Comment by garaemon** [comment]
@aginika 

check http://www.ros.org/debbuild/jade.html

**Comment by wkentaro** [comment]
Maybe `sklearn` package is not necessary at this time, because `python-sklearn` is released on apt.
```
ROS_DISTRO=jade rosdep resolve python-sklearn
#apt
python-sklearn
```
jsk_recognition can depends on `python-sklearn` in package.xml.

**Comment by wkentaro** [comment]
Sent PR

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1426
- https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/53
