### ISSUE TITLE
.cfg files need to be fixed and released

### ISSUE THREAD

**Issue by dirk-thomas** [jsk-ros-pkg/jsk_3rdparty#57]
The .cfg files in this repo need to be fixed the same as jsk-ros-pkg/jsk_common@b79ec0a1f8638a87aea774629e465cc38ef7bd94. E.g. https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/3rdparty/mini_maxwell/cfg/RosClient.cfg

These changes need to be released. Currently the Jade jobs fail since the old code falls back to the non-catkin code generation which won't generate the header in the correct location (e.g. http://build.ros.org/job/Jbin_uT64__mini_maxwell__ubuntu_trusty_amd64__binary/2/).

This will likely also be the same for the upcoming Indigo rebuild.

**Comment by k-okada** [comment]
thaks, fixed in https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/58

**Comment by dirk-thomas** [comment]
Thank you for the fast fix and release.
