### ISSUE TITLE
Fail to build assimp_devel

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_3rdparty#65]
Moved from https://github.com/jsk-ros-pkg/jsk_common/issues/1419

Anyone who is familiar with this package?

**Comment by k-okada** [comment]
@YoheiKakiuchi, please take look at this.

--
◉ Kei Okada

**Comment by YoheiKakiuchi** [comment]
Downloading zip file was failed.
It never occur in my PC.

I just restarted travis, assimp_devel was successfully built https://github.com/jsk-ros-pkg/jsk_common/pull/1417

**Comment by wkentaro** [comment]
@YoheiKakiuchi Possibly the temporary issue of yesterday. Thank you.
