### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by vrabaud** [jsk-ros-pkg/jsk_3rdparty#69]
Any ETA for that? Thx
Is assimp still needed? There is finally a newer version in Xenial:
http://packages.ubuntu.com/source/xenial/graphics/assimp

**Comment by k-okada** [comment]
@YoheiKakiuchi please check xenial version of assimp

--
◉ Kei Okada

**Comment by k-okada** [comment]
Sorry for super late, finally released
https://github.com/ros/rosdistro/pull/13106#event-841103538
