### ISSUE TITLE
Please release next version for some changes on libcmt

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_3rdparty#74]
I need this for https://github.com/jsk-ros-pkg/jsk_recognition/pull/1904

**Comment by k-okada** [comment]
may be https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/71 is ok

**Comment by k-okada** [comment]
ok done https://github.com/jsk-ros-pkg/jsk_3rdparty/commit/c6e3e14ccf9aa74c8af7cf6cc5d9f99b1045d442
