### ISSUE TITLE
collada_urdf_jsk_patch fails to build

### ISSUE THREAD

**Issue by tfoote** [jsk-ros-pkg/jsk_3rdparty#89]
http://build.ros.org/view/Jbin_uT64/job/Jbin_uT64__collada_urdf_jsk_patch__ubuntu_trusty_amd64__binary/18/console

The patch being applied appears to be out of date.

**Comment by k-okada** [comment]
Thanks
This should be fixed by
https://github.com/ros/rosdistro/pull/13985 (for indigo) and upcoming PR for jade

**Comment by furushchev** [comment]
I think this issue can be closed now.
